version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - yum update -y
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - terraform --version
      
  pre_build:
    commands:
      - export AWS_SECRET=$(aws secretsmanager get-secret-value --secret-id awssecret --query SecretString --output text)
      - export AWS_ACCESS_KEY_ID=$(echo $AWS_SECRET | jq -r .AWS_ACCESS_KEY_ID)
      - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET | jq -r .AWS_SECRET_ACCESS_KEY)
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region us-west-2
      - aws configure set default.output json
      - git clone https://github.com/akhilsathyan07/terraform-eks-aws-codepipeline.git
      - cd terraform-eks-aws-codepipeline
      - terraform init
      
  build:
    commands:
      - terraform plan 

  post_build:
    commands:
      - terraform apply --auto-approve

artifacts:
  files:
    - '**/*'
  
