version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - yum update -y
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - terraform --version
      # Set AWS Credentials and Region as environment variables
      - export AWS_ACCESS_KEY_ID=AKIAQSFUP5DOB7XUUHQH
      - export AWS_SECRET_ACCESS_KEY=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
      - export AWS_DEFAULT_REGION=us-west-2

  pre_build:
    commands:
      - git clone https://github.com/akhilsathyan07/terraform-eks-aws-codepipeline.git
      - cd terraform-eks-aws-codepipeline
      - terraform init

  build:
    commands:
      - terraform plan -out=tfplan

  post_build:
    commands:
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
