version: 0.2

phases:
  install:
    commands:
      # AWS CLI installation
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
      - aws --version
      # kubectl installation
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
      - echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - chmod +x kubectl
      - mkdir -p ~/.local/bin
      - mv ./kubectl ~/.local/bin/kubectl
      # Additional tools
      - sudo yum install wget -y
      - sudo yum update -y
      - sudo yum install -y python3
      - sudo yum install python-pip -y
      - python3 -m ensurepip

  pre_build:
    commands:
      # Setup kube-bench
      - wget https://github.com/aquasecurity/kube-bench/releases/download/v0.3.0/kube-bench_0.3.0_linux_amd64.tar.gz
      - tar -xvf kube-bench_0.3.0_linux_amd64.tar.gz
      # Setup kube-hunter
      - pip3 install --user kube-hunter
      - echo 'PATH=$PATH:$HOME/.local/bin' >> ~/.bash_profile
      - echo 'export PATH' >> ~/.bash_profile
      - source ~/.bash_profile

  build:
    commands:
      - kubectl version --client
      - aws eks describe-cluster --region us-west-2 --name eks-cluster-07 --query cluster.status
      - aws eks update-kubeconfig --region us-west-2 --name eks-cluster-07
      - kubectl get nodes
      - kubectl apply -f jobbench.yml
      - kubectl get pods

  post_build:
    commands:
      - POD_NAME=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" | grep '^kube-bench' | head -n 1)
      - echo "Found pod: $POD_NAME"
      - kubectl logs $POD_NAME > kube-bench-log.txt
      # Add any additional commands to handle the log file, such as storing it as an artifact
