version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update && apt-get install -y unzip software-properties-common
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install terraform
      - terraform --version

  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform plan -out=tfplan

  post_build:
    commands:
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'

