version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - yum update -y
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - terraform --version
      
  pre_build:
    commands:
      - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
      - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
      - aws configure set default.region us-west-2
      - aws configure set default.output json
      - aws s3 ls
      - aws sts get-caller-identity
      - terraform init
      
  build:
    commands:
      - terraform plan 

  post_build:
    commands:
      - terraform apply --auto-approve

artifacts:
  files:
    - '**/*'
  
